version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: beauty-salon-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=BeautySalonCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: beauty-salon-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=beauty_salon
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend-go:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    container_name: beauty-salon-backend-go
    ports:
      - "8082:8080"
    environment:
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=beauty_salon
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend-java-reactive:
    build:
      context: ./backend-java-reactive
      dockerfile: Dockerfile
    container_name: beauty-salon-backend-reactive
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_CASSANDRA_PORT=9042
      - SPRING_CASSANDRA_KEYSPACE_NAME=beauty_salon
      - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: beauty-salon-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - beauty-salon-network

volumes:
  cassandra_data:

networks:
  beauty-salon-network:
    driver: bridge
