version: '3.8'

services:
  cassandra:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: beauty-salon-cassandra-custom
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=beauty_salon_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s  # Mais tempo para inicialização
    restart: unless-stopped
    networks:
      - beauty-salon-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: beauty-salon-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=beauty_salon
      - CASSANDRA_LOCAL_DATACENTER=datacenter1
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  backend-nodejs:
    build:
      context: ./backend-nodejs
      dockerfile: Dockerfile
    container_name: beauty-salon-backend-nodejs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=beauty_salon
      - CASSANDRA_LOCAL_DATACENTER=datacenter1
      - CACHE_TTL=600000
      - CACHE_MAX_KEYS=1000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - CORS_ORIGIN=*
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  cassandra_data:
    driver: local

networks:
  beauty-salon-network:
    driver: bridge
