version: '3.8'

services:
  # Cassandra Database
  cassandra:
    image: cassandra:4.1
    container_name: beauty-salon-cassandra-reactive
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=BeautySalonCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  # Java Reactive Backend
  backend-java-reactive:
    build:
      context: ./backend-java-reactive
      dockerfile: Dockerfile
    container_name: beauty-salon-backend-reactive
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_CASSANDRA_PORT=9042
      - SPRING_CASSANDRA_KEYSPACE_NAME=beauty_salon
      - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_CASSANDRA_SCHEMA_ACTION=CREATE_IF_NOT_EXISTS
      - JAVA_OPTS=-Xms512m -Xmx1024m
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: beauty-salon-frontend-reactive
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8085/api
      - REACT_APP_ENVIRONMENT=docker
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend-java-reactive:
        condition: service_healthy
    networks:
      - beauty-salon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  beauty-salon-network:
    driver: bridge
    name: beauty-salon-reactive-network

volumes:
  cassandra_data:
    driver: local
    name: beauty-salon-cassandra-reactive-data
