done = function(summary, latency, requests)
    io.write("------------------------------\n")
    io.write("Duration: " .. summary.duration / 1000 .. " ms\n")
    io.write("Requests: " .. summary.requests .. "\n")
    io.write("Bytes: " .. summary.bytes .. "\n")
    io.write("Errors: " .. (summary.errors.connect + summary.errors.read + summary.errors.write + summary.errors.timeout) .. "\n")
    io.write("------------------------------\n")
    io.write("Latency Min: " .. string.format("%.2f", latency.min / 1000) .. " ms\n")
    io.write("Latency Max: " .. string.format("%.2f", latency.max / 1000) .. " ms\n")
    io.write("Latency Mean: " .. string.format("%.2f", latency.mean / 1000) .. " ms\n")
    io.write("Latency Stdev: " .. string.format("%.2f", latency.stdev / 1000) .. " ms\n")
    io.write("Latency P50: " .. string.format("%.2f", latency:percentile(50) / 1000) .. " ms\n")
    io.write("Latency P75: " .. string.format("%.2f", latency:percentile(75) / 1000) .. " ms\n")
    io.write("Latency P90: " .. string.format("%.2f", latency:percentile(90) / 1000) .. " ms\n")
    io.write("Latency P95: " .. string.format("%.2f", latency:percentile(95) / 1000) .. " ms\n")
    io.write("Latency P99: " .. string.format("%.2f", latency:percentile(99) / 1000) .. " ms\n")
    io.write("Latency P99.9: " .. string.format("%.2f", latency:percentile(99.9) / 1000) .. " ms\n")
    io.write("Latency P99.99: " .. string.format("%.2f", latency:percentile(99.99) / 1000) .. " ms\n")
end
