version: '3.8'

services:
  backend-nodejs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=beauty_salon
      - CASSANDRA_LOCAL_DATACENTER=datacenter1
      - CACHE_TTL=600000
      - CACHE_MAX_KEYS=1000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - CORS_ORIGIN=*
    depends_on:
      cassandra:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - beauty-salon-network

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=beauty_salon_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ../database/init.cql:/docker-entrypoint-initdb.d/init.cql
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - beauty-salon-network

volumes:
  cassandra_data:
    driver: local

networks:
  beauty-salon-network:
    driver: bridge
