spring:
  application:
    name: beauty-salon-backend
  flyway:
    enabled: false  # Disabled because we use Cassandra (no JDBC DataSource). We'll run Flyway migrations explicitly.
  
  cassandra:
    keyspace-name: ~  # Don't specify keyspace initially - let migration runner create it
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    pool:
      max-requests-per-connection: 1024
      max-connections: 8
      heartbeat-interval: 30s
      idle-timeout: 120s
    request:
      timeout: 5s
      consistency: LOCAL_QUORUM
    connection:
      connect-timeout: 5s
      init-query-timeout: 5s
  
  cache:
    type: simple
    cache-names: customers,services,staff,appointments
    simple:
      spec: maximumSize=1000,expireAfterWrite=10m

  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches,httptrace,threaddump,heapdump
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  threads:
    virtual:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
    cache:
      metric-name: cache.stats
    cassandra:
      metric-name: cassandra.stats
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.beautysalon: DEBUG
    org.springframework.data.cassandra: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  cassandra:
    contact-points: cassandra
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: ~
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: virtual-threads
  threads:
    virtual:
      enabled: true
  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: beauty_salon_test
    connection:
      pool:
        local:
          core-connections: 4
          max-connections: 16
        remote:
          core-connections: 2
          max-connections: 8
      connect-timeout: 10s
      read-timeout: 30s
    request:
      timeout: 30s
      page-size: 5000
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=2000,expireAfterAccess=10m,expireAfterWrite=30m
    cache-names:
      - customers
      - services
      - staff
      - appointments
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: virtual-threads-g1gc
  threads:
    virtual:
      enabled: true
  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: beauty_salon_test
    connection:
      pool:
        local:
          core-connections: 4
          max-connections: 16
        remote:
          core-connections: 2
          max-connections: 8
      connect-timeout: 10s
      read-timeout: 30s
    request:
      timeout: 30s
      page-size: 5000
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=2000,expireAfterAccess=10m,expireAfterWrite=30m
    cache-names:
      - customers
      - services
      - staff
      - appointments

server:
  port: 8080
  tomcat:
    threads:
      max: 1000        # High thread count for virtual threads
      min-spare: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches,httptrace,threaddump,heapdump
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true

logging:
  level:
    com.beautysalon: INFO  # Less verbose logging for performance
    org.springframework.data.cassandra: WARN
