server:
  port: 8087

spring:
  application:
    name: springdoc-test

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springdoc: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
